// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PicknPayAspNetCoreWebApi.Models;

namespace PicknPayAspNetCoreWebApi.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20190910084742_ProductMigration")]
    partial class ProductMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PicknPayAspNetCoreWebApi.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CartItemCount")
                        .HasColumnType("int");

                    b.Property<string>("ProductBarcode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductBrand")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductCategory")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductMass")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductPreviousPrice")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProductPrice")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
